theme: jekyll-theme-midnight
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docker-note.md
  - dotnet-note.md
  - angular-note.md
  - linux-note.md
